COMMENT ON TABLE "platform"."auth_sessions" IS '服务端登录会话表，保存当前系统的登录态与最小权限范围。';
COMMENT ON COLUMN "platform"."auth_sessions"."session_id" IS '服务端会话 ID。';
COMMENT ON COLUMN "platform"."auth_sessions"."user_id" IS '当前登录用户 ID。';
COMMENT ON COLUMN "platform"."auth_sessions"."display_name" IS '当前登录用户显示名。';
COMMENT ON COLUMN "platform"."auth_sessions"."organization_id" IS '当前会话归属组织 ID。';
COMMENT ON COLUMN "platform"."auth_sessions"."project_ids" IS '当前会话允许访问的项目 ID 列表。';
COMMENT ON COLUMN "platform"."auth_sessions"."area_ids" IS '历史保留的区域范围字段，后续逐步淡出。';
COMMENT ON COLUMN "platform"."auth_sessions"."role_codes" IS '当前会话角色编码列表。';
COMMENT ON COLUMN "platform"."auth_sessions"."expires_at" IS '会话过期时间。';
COMMENT ON COLUMN "platform"."auth_sessions"."created_at" IS '会话创建时间。';

COMMENT ON TABLE "platform"."analysis_sessions" IS '分析会话主表，保存用户问题、上下文快照与作用域。';
COMMENT ON COLUMN "platform"."analysis_sessions"."id" IS '分析会话 ID。';
COMMENT ON COLUMN "platform"."analysis_sessions"."owner_user_id" IS '发起该分析会话的用户 ID。';
COMMENT ON COLUMN "platform"."analysis_sessions"."organization_id" IS '分析会话组织范围。';
COMMENT ON COLUMN "platform"."analysis_sessions"."project_ids" IS '分析会话项目范围。';
COMMENT ON COLUMN "platform"."analysis_sessions"."area_ids" IS '历史保留的区域范围字段。';
COMMENT ON COLUMN "platform"."analysis_sessions"."question_text" IS '用户原始提问文本。';
COMMENT ON COLUMN "platform"."analysis_sessions"."saved_context" IS '当前保存的结构化分析上下文。';
COMMENT ON COLUMN "platform"."analysis_sessions"."status" IS '分析会话状态。';
COMMENT ON COLUMN "platform"."analysis_sessions"."created_at" IS '分析会话创建时间。';
COMMENT ON COLUMN "platform"."analysis_sessions"."updated_at" IS '分析会话最后更新时间。';

COMMENT ON TABLE "platform"."analysis_execution_snapshots" IS '分析执行快照表，保存单次执行的计划、步骤结果与结论状态。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."execution_id" IS '执行快照 ID。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."session_id" IS '所属分析会话 ID。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."owner_user_id" IS '执行所属用户 ID。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."follow_up_id" IS '若由追问触发，则记录追问 ID。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."status" IS '执行状态。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."plan_snapshot" IS '执行时使用的计划快照。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."step_results" IS '步骤执行结果列表。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."conclusion_state" IS '结论聚合状态。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."result_blocks" IS '工作台展示使用的结果块。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."mobile_projection" IS '移动端摘要投影。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."failure_point" IS '失败定位信息。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."created_at" IS '执行创建时间。';
COMMENT ON COLUMN "platform"."analysis_execution_snapshots"."updated_at" IS '执行最后更新时间。';

COMMENT ON TABLE "platform"."analysis_session_follow_ups" IS '分析追问表，保存多轮追问链路、上下文继承与计划版本。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."id" IS '追问 ID。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."session_id" IS '所属分析会话 ID。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."owner_user_id" IS '追问发起用户 ID。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."question_text" IS '追问文本。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."parent_follow_up_id" IS '父级追问 ID，用于形成追问链。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."referenced_execution_id" IS '追问所引用的执行结果 ID。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."referenced_conclusion_title" IS '追问引用的结论标题。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."referenced_conclusion_summary" IS '追问引用的结论摘要。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."result_execution_id" IS '该追问最终生成的执行结果 ID。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."inherited_context" IS '继承自上一轮的上下文基线。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."merged_context" IS '合并用户修正后的上下文。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."created_order" IS '同一会话内追问顺序号。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."plan_version" IS '当前追问计划版本号。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."current_plan_snapshot" IS '当前追问计划快照。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."previous_plan_snapshot" IS '上一版计划快照。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."current_plan_diff" IS '计划变更差异。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."created_at" IS '追问创建时间。';
COMMENT ON COLUMN "platform"."analysis_session_follow_ups"."updated_at" IS '追问最后更新时间。';

COMMENT ON TABLE "platform"."audit_events" IS '平台审计事件表，记录授权、分析、工具调用等关键事件。';
COMMENT ON COLUMN "platform"."audit_events"."id" IS '审计事件 ID。';
COMMENT ON COLUMN "platform"."audit_events"."user_id" IS '事件责任用户 ID。';
COMMENT ON COLUMN "platform"."audit_events"."organization_id" IS '事件所属组织 ID。';
COMMENT ON COLUMN "platform"."audit_events"."session_id" IS '关联的分析会话 ID。';
COMMENT ON COLUMN "platform"."audit_events"."event_type" IS '审计事件类型。';
COMMENT ON COLUMN "platform"."audit_events"."event_result" IS '事件结果，如 success/denied/failure。';
COMMENT ON COLUMN "platform"."audit_events"."event_source" IS '事件来源，如 route-handler/worker/tooling。';
COMMENT ON COLUMN "platform"."audit_events"."correlation_id" IS '跨链路关联 ID。';
COMMENT ON COLUMN "platform"."audit_events"."payload" IS '审计附加上下文。';
COMMENT ON COLUMN "platform"."audit_events"."created_at" IS '事件发生时间。';
COMMENT ON COLUMN "platform"."audit_events"."retention_until" IS '审计记录保留截止时间。';

COMMENT ON TABLE "platform"."graph_sync_runs" IS '图谱同步任务运行记录。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."id" IS '同步运行 ID。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."mode" IS '同步模式，如 bootstrap/incremental/consistency-sweep。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."status" IS '同步运行状态。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."scope_type" IS '本次同步作用域类型。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."scope_key" IS '本次同步作用域标识。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."trigger_type" IS '触发方式。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."triggered_by" IS '触发人或触发器。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."cursor_snapshot" IS '同步游标快照。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."nodes_written" IS '写入节点数量。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."edges_written" IS '写入边数量。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."error_summary" IS '错误摘要。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."error_detail" IS '错误详情。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."started_at" IS '同步开始时间。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."finished_at" IS '同步结束时间。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."created_at" IS '记录创建时间。';
COMMENT ON COLUMN "platform"."graph_sync_runs"."updated_at" IS '记录更新时间。';

COMMENT ON TABLE "platform"."graph_sync_cursors" IS '图谱同步游标表，记录各数据源当前扫描位置。';
COMMENT ON COLUMN "platform"."graph_sync_cursors"."source_name" IS '游标对应的数据源名称。';
COMMENT ON COLUMN "platform"."graph_sync_cursors"."cursor_time" IS '按时间推进的游标值。';
COMMENT ON COLUMN "platform"."graph_sync_cursors"."cursor_pk" IS '按主键推进的游标值。';
COMMENT ON COLUMN "platform"."graph_sync_cursors"."last_run_id" IS '最后一次推进该游标的同步运行 ID。';
COMMENT ON COLUMN "platform"."graph_sync_cursors"."updated_at" IS '游标更新时间。';

COMMENT ON TABLE "platform"."graph_sync_dirty_scopes" IS '待补偿或待重建的脏作用域列表。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."id" IS '脏作用域记录 ID。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."scope_type" IS '脏作用域类型。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."scope_key" IS '脏作用域标识。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."reason" IS '标记为脏的原因。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."source_name" IS '来源数据表或来源任务。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."source_pk" IS '来源记录主键。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."source_progress" IS '来源进度快照。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."first_detected_at" IS '首次发现时间。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."last_detected_at" IS '最近一次发现时间。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."status" IS '当前处理状态。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."attempt_count" IS '重试次数。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."last_run_id" IS '最后一次处理它的运行 ID。';
COMMENT ON COLUMN "platform"."graph_sync_dirty_scopes"."error_summary" IS '最近一次处理失败摘要。';

COMMENT ON TABLE "platform"."ontology_versions" IS '本体治理版本表，记录治理定义的发布批次与生命周期。';
COMMENT ON COLUMN "platform"."ontology_versions"."id" IS '本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_versions"."semver" IS '语义化版本号。';
COMMENT ON COLUMN "platform"."ontology_versions"."display_name" IS '版本显示名。';
COMMENT ON COLUMN "platform"."ontology_versions"."status" IS '版本状态，如 draft/review/approved/deprecated/retired。';
COMMENT ON COLUMN "platform"."ontology_versions"."description" IS '版本说明。';
COMMENT ON COLUMN "platform"."ontology_versions"."published_at" IS '版本发布时间。';
COMMENT ON COLUMN "platform"."ontology_versions"."deprecated_at" IS '版本废弃时间。';
COMMENT ON COLUMN "platform"."ontology_versions"."retired_at" IS '版本退役时间。';
COMMENT ON COLUMN "platform"."ontology_versions"."created_by" IS '版本创建人。';
COMMENT ON COLUMN "platform"."ontology_versions"."created_at" IS '版本创建时间。';
COMMENT ON COLUMN "platform"."ontology_versions"."updated_at" IS '版本更新时间。';

COMMENT ON TABLE "platform"."ontology_entity_definitions" IS '本体实体定义表。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."business_key" IS '实体稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."display_name" IS '实体显示名。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."description" IS '实体业务说明。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."synonyms" IS '实体同义词列表。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."parent_business_key" IS '父实体业务键。';
COMMENT ON COLUMN "platform"."ontology_entity_definitions"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_metric_definitions" IS '本体指标定义表。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."business_key" IS '指标稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."display_name" IS '指标显示名。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."description" IS '指标业务定义。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."applicable_subject_keys" IS '适用业务主题列表。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."default_aggregation" IS '默认聚合方式。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."unit" IS '指标单位。';
COMMENT ON COLUMN "platform"."ontology_metric_definitions"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_factor_definitions" IS '本体候选因素定义表。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."business_key" IS '因素稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."display_name" IS '因素显示名。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."description" IS '因素业务定义。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."category" IS '因素分类。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."related_metric_keys" IS '关联指标业务键列表。';
COMMENT ON COLUMN "platform"."ontology_factor_definitions"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_plan_step_templates" IS '本体计划步骤模板表。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."business_key" IS '计划步骤稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."display_name" IS '计划步骤显示名。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."description" IS '计划步骤说明。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."intent_types" IS '适用意图类型列表。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."required_capabilities" IS '所需能力列表。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."sort_order" IS '模板默认排序。';
COMMENT ON COLUMN "platform"."ontology_plan_step_templates"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_metric_variants" IS '本体指标口径变体定义表。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."parent_metric_definition_id" IS '所属父指标定义 ID。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."business_key" IS '口径变体稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."display_name" IS '口径变体显示名。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."description" IS '口径变体业务定义。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."semantic_discriminator" IS '区分不同口径的核心语义标识。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."cube_view_mapping" IS '到 Cube 语义查询层的映射配置。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."filter_template" IS '适用过滤模板。';
COMMENT ON COLUMN "platform"."ontology_metric_variants"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_time_semantics" IS '本体时间语义定义表。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."business_key" IS '时间语义稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."display_name" IS '时间语义显示名。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."description" IS '时间语义说明。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."semantic_type" IS '时间语义类型。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."entity_date_field_mapping" IS '业务实体日期字段映射。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."cube_time_dimension_mapping" IS 'Cube 时间维度映射。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."calculation_rule" IS '时间语义计算规则。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."default_granularity" IS '默认时间粒度。';
COMMENT ON COLUMN "platform"."ontology_time_semantics"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_causality_edges" IS '本体因果边定义表。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."business_key" IS '因果边稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."display_name" IS '因果边显示名。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."description" IS '因果边业务说明。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."source_entity_key" IS '源实体业务键。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."target_entity_key" IS '目标实体业务键。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."causality_type" IS '因果关系类型。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."is_attribution_path_enabled" IS '是否允许进入归因路径。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."default_weight" IS '默认归因权重。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."neo4j_relationship_types" IS '映射到 Neo4j 的关系类型列表。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."temporal_constraints" IS '时间约束。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."filter_conditions" IS '业务过滤条件。';
COMMENT ON COLUMN "platform"."ontology_causality_edges"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "platform"."ontology_evidence_type_definitions" IS '本体证据类型定义表。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."ontology_version_id" IS '所属本体版本 ID。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."business_key" IS '证据类型稳定业务键。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."display_name" IS '证据类型显示名。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."description" IS '证据类型说明。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."status" IS '定义生命周期状态。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."evidence_category" IS '证据类别。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."renderer_config" IS '渲染配置。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."data_source_config" IS '数据源配置。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."default_priority" IS '默认展示优先级。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."is_interactive" IS '是否支持交互式探索。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."template_schema" IS '标准化证据模板。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."validation_rules" IS '证据数据校验规则。';
COMMENT ON COLUMN "platform"."ontology_evidence_type_definitions"."metadata" IS '扩展元数据。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_system_user" IS 'ERP 同步过来的用户表，是当前登录鉴权的上游来源之一。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."source_id" IS 'ERP 用户主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."organization_id" IS '用户所属组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."user_account" IS 'ERP 登录账号。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."password" IS 'ERP 原始密码字段（历史字段，通常不直接使用）。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."user_telephone" IS '用户手机号。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."user_password" IS 'ERP 口径下的加密密码字段，当前目录登录主要比对该字段。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."user_state" IS '用户状态。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."user_type" IS '用户类型。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."is_deleted" IS '是否删除。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."is_actived" IS '是否激活。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."sync_date" IS '同步时间。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_user"."sys_date" IS '数仓分区日期。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_system_organization" IS 'ERP 同步组织表，是组织、项目和层级 scope 推导的核心来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."source_id" IS 'ERP 组织主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_parent_id" IS '父组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_name" IS '组织名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_short_name" IS '组织简称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_code" IS '组织编码。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_path" IS '组织祖先链路径，用于上级组织继承下级项目。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_level" IS '组织层级。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_dimension" IS '组织维度。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_scope" IS '组织业务范围。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."organization_nature" IS '组织性质，常用于识别 propertyProject 等项目节点。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."data_analysis_type" IS '数据分析类型标识。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_system_organization"."sys_date" IS '数仓分区日期。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_precinct" IS 'ERP 项目/小区表，是项目级 scope 和收费统计的重要维度表。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."precinct_id" IS '项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."org_id" IS '上游组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."area_id" IS '区域 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."precinct_name" IS '项目/小区名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."organization_id" IS '映射到组织表的组织主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_precinct"."delete_flag" IS '删除标志。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_owner" IS 'ERP 业主表，用于项目、房屋与业主事实关联。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."record_id" IS '业主记录主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."precinct_id" IS '所属项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."house_id" IS '所属房屋 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."owner_id" IS '业主 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."owner_name" IS '业主姓名。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."owner_type" IS '业主类型。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_owner"."is_current" IS '是否当前有效业主。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_chargeitem" IS 'ERP 收费项目维度表。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_chargeitem"."charge_item_id" IS '收费项目 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_chargeitem"."charge_item_code" IS '收费项目编码。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_chargeitem"."charge_item_name" IS '收费项目名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_chargeitem"."charge_item_type" IS '收费项目类型编码。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_chargeitem"."charge_item_type_name" IS '收费项目类型名称。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_charge" IS 'ERP 应收事实表，是收缴率、应收金额、尾欠口径的主要来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."record_id" IS '应收记录主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."organization_id" IS '组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."precinct_id" IS '项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."owner_id" IS '业主 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."charge_item_id" IS '收费项目 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."should_account_book" IS '应收账期，项目口径的核心时间语义来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."calc_start_date" IS '计费开始日期。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."calc_end_date" IS '计费结束日期，尾欠口径的重要时间语义来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."calc_end_year" IS '计费结束年份。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."actual_charge_sum" IS '应收金额。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."paid_charge_sum" IS '已收金额。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."arrears" IS '欠费金额。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."is_check" IS '审核状态。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_charge"."is_delete" IS '删除标志。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_bill" IS 'ERP 实收事实表，是实收金额与 payment-date 语义的主要来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."record_id" IS '实收记录主键。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."organization_id" IS '组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."precinct_id" IS '项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."owner_id" IS '业主 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."charge_item_id" IS '收费项目 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."should_account_book" IS '应收账期。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."calc_end_date" IS '账单截止日期。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."charge_paid" IS '实收金额。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."operator_date" IS '缴款日期，payment-date 语义的首选来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."paid_year" IS '缴款年份（operator_date 缺失时的兜底字段）。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."paid_month" IS '缴款月份（operator_date 缺失时的兜底字段）。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."paid_day" IS '缴款日（operator_date 缺失时的兜底字段）。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."is_enter_account" IS '是否入账。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."subject_code" IS '科目标识。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."precinct_collection_type" IS '项目代收类型标识。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_bill"."refund_status" IS '退款状态。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_services" IS 'ERP 工单服务表，是工单数量、投诉量、满意度和时效指标的主要来源。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."services_no" IS '工单编号。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."organization_id" IS '组织 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."precinct_id" IS '项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."customer_name" IS '客户姓名。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."content" IS '工单内容。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."create_date_time" IS '工单创建时间。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."dispatching_date" IS '派单时间。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."accept_date" IS '接单时间。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."accomplish_date" IS '工单完成时间。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."service_status" IS '工单状态编码。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."service_status_name" IS '工单状态名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."service_type_name" IS '工单类型名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."service_style_name" IS '工单风格/业务类型名称，如投诉、报修。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."satisfaction" IS '满意度分值。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_services"."satisfaction_eval" IS '满意度评价枚举。';

COMMENT ON TABLE "erp_staging"."dw_datacenter_house" IS 'ERP 房屋表，用于项目、房屋与业主/收费事实关联。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."house_id" IS '房屋 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."precinct_id" IS '所属项目/小区 ID。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."house_name" IS '房屋名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."room_type" IS '房间类型编码。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."room_type_name" IS '房间类型名称。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."charge_area" IS '计费面积。';
COMMENT ON COLUMN "erp_staging"."dw_datacenter_house"."build_area" IS '建筑面积。';
