CREATE SCHEMA "erp_staging";
--> statement-breakpoint
CREATE SCHEMA "platform";
--> statement-breakpoint
CREATE TABLE "platform"."analysis_execution_snapshots" (
	"execution_id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"follow_up_id" text,
	"ontology_version_id" text,
	"ontology_version_binding_source" text DEFAULT 'legacy/unknown' NOT NULL,
	"status" text NOT NULL,
	"plan_snapshot" jsonb NOT NULL,
	"step_results" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"conclusion_state" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"result_blocks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"mobile_projection" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"failure_point" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."analysis_session_follow_ups" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"question_text" text NOT NULL,
	"parent_follow_up_id" text,
	"referenced_execution_id" text NOT NULL,
	"referenced_conclusion_title" text,
	"referenced_conclusion_summary" text,
	"result_execution_id" text,
	"ontology_version_id" text,
	"ontology_version_binding_source" text DEFAULT 'legacy/unknown' NOT NULL,
	"inherited_context" jsonb NOT NULL,
	"merged_context" jsonb NOT NULL,
	"created_order" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "platform"."analysis_session_follow_ups_created_order_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan_version" integer,
	"current_plan_snapshot" jsonb,
	"previous_plan_snapshot" jsonb,
	"current_plan_diff" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."analysis_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_user_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"project_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"area_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"question_text" text NOT NULL,
	"saved_context" jsonb NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."analysis_ui_message_projections" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"execution_id" text NOT NULL,
	"follow_up_id" text,
	"history_round_id" text,
	"projection_version" integer NOT NULL,
	"part_schema_version" integer NOT NULL,
	"contract_version" integer NOT NULL,
	"status" text NOT NULL,
	"is_terminal" boolean NOT NULL,
	"stream_cursor" jsonb DEFAULT '{"lastSequence":0,"lastEventId":null}'::jsonb NOT NULL,
	"messages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recovery_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."audit_events" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"session_id" text,
	"event_type" text NOT NULL,
	"event_result" text NOT NULL,
	"event_source" text NOT NULL,
	"correlation_id" text NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"retention_until" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."auth_sessions" (
	"session_id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"display_name" text NOT NULL,
	"organization_id" text NOT NULL,
	"project_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"area_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"role_codes" text[] DEFAULT '{}'::text[] NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_chargeitem" (
	"record_id" bigint,
	"enterprise_id" text,
	"organization_id" text,
	"data_source" text,
	"charge_item_id" text PRIMARY KEY NOT NULL,
	"charge_item_code" text,
	"charge_item_name" text NOT NULL,
	"charge_item_type" text,
	"charge_item_type_name" text,
	"tax_rate" numeric(3, 2),
	"item_group_id" bigint,
	"item_detail_group_id" bigint,
	"cash_flow_group_id" bigint,
	"charge_item_class" integer,
	"charge_item_class_name" text,
	"path" text,
	"create_date" timestamp with time zone,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone,
	"delete_flag" integer,
	"create_user_id" bigint,
	"create_user_name" text,
	"create_date_time" date,
	"update_user_id" bigint,
	"update_user_name" text,
	"update_date_time" date,
	"charge_item_out_type" text,
	"one_level_charge_item_name" text
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_house" (
	"record_id" bigint,
	"enterprise_id" text,
	"data_source" text,
	"org_id" text,
	"precinct_id" text,
	"precinct_name" text,
	"house_id" text PRIMARY KEY NOT NULL,
	"house_name" text,
	"room_type" text,
	"room_type_name" text,
	"house_type" text,
	"charge_area" numeric,
	"build_area" numeric,
	"is_show" integer,
	"is_spilt" integer,
	"is_virtual" integer,
	"stage" text,
	"rent_stage" text,
	"decorate_stage" text,
	"building_id" text,
	"regional_company_id" text,
	"area_id" text,
	"cluster_id" text,
	"business_cluster_id" text,
	"unit_id" text,
	"is_delete" integer,
	"is_block_up" integer,
	"create_date" timestamp with time zone,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_system_organization" (
	"source_id" bigint PRIMARY KEY NOT NULL,
	"enterprise_id" bigint,
	"group_id" bigint,
	"company_id" bigint,
	"department_id" bigint,
	"organization_parent_id" bigint,
	"organization_name" text NOT NULL,
	"organization_short_name" text,
	"organization_code" text,
	"organization_type" integer,
	"organization_enable_state" integer,
	"organization_path" text,
	"organization_level" integer,
	"organization_order_column" integer,
	"is_deleted" integer,
	"remark" text,
	"version_id" bigint,
	"create_user_id" bigint,
	"create_user_name" text,
	"create_time" timestamp with time zone,
	"update_user_id" bigint,
	"update_user_name" text,
	"update_time" timestamp with time zone,
	"sync_department_id" text,
	"sync_organization_id" text,
	"sync_organization_parent_id" text,
	"sync_status" integer,
	"organization_dimension" text,
	"organization_dimension_alias_name" text,
	"organization_scope" text,
	"organization_manager_id" text,
	"organization_part_manager_id" text,
	"organization_hr_type_code" text,
	"organization_hierarchical_class_code" text,
	"organization_stage_code" text,
	"organization_stage_level_code" text,
	"organization_source" text,
	"organization_nature" text,
	"data_analysis_type" text,
	"sys_date" date
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_owner" (
	"record_id" bigint PRIMARY KEY NOT NULL,
	"enterprise_id" text,
	"data_source" text,
	"org_id" text,
	"precinct_id" text NOT NULL,
	"precinct_name" text,
	"house_id" text,
	"house_name" text,
	"owner_id" text NOT NULL,
	"owner_name" text NOT NULL,
	"owner_type" text,
	"is_current" text,
	"is_delete" integer,
	"create_date" timestamp with time zone,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_bill" (
	"record_id" bigint PRIMARY KEY NOT NULL,
	"db_id" integer,
	"enterprise_id" text,
	"organization_id" text NOT NULL,
	"data_source" text,
	"charge_payment_id" text,
	"charge_detail_id" text,
	"precinct_id" text,
	"precinct_name" text,
	"house_id" text,
	"house_name" text,
	"room_type" text,
	"owner_id" text,
	"owner_name" text,
	"charge_item_id" text,
	"charge_item_code" text,
	"charge_item_name" text,
	"calc_start_date" timestamp with time zone,
	"calc_end_date" timestamp with time zone,
	"calc_end_year" integer,
	"should_account_book" integer,
	"account_book" integer,
	"actual_account_book" integer,
	"charge_paid" numeric,
	"discount" numeric,
	"delay_sum" numeric,
	"operator_date" timestamp with time zone,
	"paid_year" integer,
	"paid_month" integer,
	"paid_day" integer,
	"is_enter_account" text,
	"charge_area" numeric,
	"subject_code" text,
	"source_income" text,
	"square_type_id" text,
	"square_type_name" text,
	"is_canceled" text,
	"is_delete" integer,
	"data_type" integer,
	"precinct_collection_type" integer,
	"refund_status" text,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone,
	"is_account" integer
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_precinct" (
	"record_id" bigint,
	"enterprise_id" text,
	"data_source" text,
	"org_id" text,
	"area_id" text,
	"area_name" text,
	"precinct_id" text PRIMARY KEY NOT NULL,
	"precinct_no" text,
	"precinct_name" text NOT NULL,
	"delivery_time" timestamp with time zone,
	"province_id" text,
	"city_id" text,
	"area_city_id" text,
	"street_id" text,
	"pro_nature" text,
	"check_merger" text,
	"check_old_precinct" text,
	"old_tax_rate" numeric(3, 2),
	"precinct_type" text,
	"precinct_type_name" text,
	"is_delete" integer,
	"create_date" timestamp with time zone,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone,
	"contract_area" numeric,
	"green_area" numeric,
	"nozzle_area" numeric,
	"pay_charge_area" numeric,
	"precinct_area" text,
	"total_house_holder" integer,
	"parking_amount" integer,
	"organization_id" bigint,
	"delete_flag" integer,
	"create_user_id" bigint,
	"create_user_name" text,
	"create_date_time" date,
	"update_user_id" bigint,
	"update_user_name" text,
	"update_date_time" date
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_charge" (
	"record_id" bigint PRIMARY KEY NOT NULL,
	"db_id" integer,
	"enterprise_id" text,
	"organization_id" text NOT NULL,
	"data_source" text,
	"charge_detail_id" text,
	"precinct_id" text,
	"precinct_name" text,
	"house_id" text,
	"house_name" text,
	"room_type" text,
	"charge_area" numeric,
	"owner_id" text,
	"owner_name" text,
	"charge_item_id" text,
	"charge_item_code" text,
	"charge_item_name" text,
	"should_account_book" integer,
	"should_charge_date" timestamp with time zone,
	"calc_start_date" timestamp with time zone,
	"calc_end_date" timestamp with time zone,
	"calc_end_year" integer,
	"amount" numeric,
	"actual_charge_sum" numeric,
	"charge_sum" numeric,
	"discount" numeric,
	"delay_sum" numeric,
	"delay_discount" numeric,
	"paid_charge_sum" numeric,
	"arrears" numeric,
	"is_check" text,
	"is_estate" integer,
	"is_delete" integer,
	"create_date" timestamp with time zone,
	"update_date" timestamp with time zone,
	"sync_date" timestamp with time zone,
	"is_freezed" integer,
	"discount_date" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_services" (
	"record_id" bigint,
	"enterprise_id" text,
	"organization_id" text NOT NULL,
	"data_source" text,
	"precinct_id" text,
	"precinct_name" text,
	"house_id" text,
	"customer_id" integer,
	"customer_house_id" integer,
	"customer_house_name" text,
	"customer_name" text,
	"house_name" text,
	"services_no" text PRIMARY KEY NOT NULL,
	"content" text,
	"create_user_name" text,
	"create_date_time" timestamp with time zone,
	"update_date_time" timestamp with time zone,
	"is_delete" integer,
	"create_year" integer,
	"create_month" integer,
	"dispatching_user_name" text,
	"dispatching_date" timestamp with time zone,
	"accept_user_name" text,
	"accept_date" timestamp with time zone,
	"arrive_date" timestamp with time zone,
	"reception_date" timestamp with time zone,
	"accomplish_user_name" text,
	"accomplish_date" timestamp with time zone,
	"service_status" text,
	"service_status_name" text,
	"service_type_id" text,
	"service_type_name" text,
	"service_source_id" text,
	"service_source_name" text,
	"service_style_id" text,
	"service_style_name" text,
	"is_completed" text,
	"is_over_time" text,
	"is_reprocess" text,
	"is_return_visit" text,
	"satisfaction" integer,
	"sync_date" timestamp with time zone,
	"accept_over_time" integer,
	"satisfaction_eval" integer,
	"service_pay_type_id" integer,
	"one_type_name" text,
	"second_type_name" text,
	"three_type_name" text,
	"service_kind_id" text,
	"service_kind_id_name" text
);
--> statement-breakpoint
CREATE TABLE "erp_staging"."dw_datacenter_system_user" (
	"source_id" bigint PRIMARY KEY NOT NULL,
	"enterprise_id" bigint,
	"organization_id" bigint,
	"group_id" bigint,
	"company_id" bigint,
	"department_id" bigint,
	"sentry_id" text,
	"sentry_name" text,
	"user_account" text,
	"password" text,
	"user_telephone" text,
	"user_password" text,
	"user_birthday" timestamp with time zone,
	"user_hiredate" timestamp with time zone,
	"user_state" text,
	"user_type" integer,
	"user_certificate_type" text,
	"user_certificate_number" text,
	"user_picurl" text,
	"is_deleted" integer,
	"is_actived" text,
	"remark" text,
	"enable2_fa" integer,
	"qw_user_id" text,
	"qw_open_id" text,
	"sync_date" timestamp with time zone,
	"sys_date" date
);
--> statement-breakpoint
CREATE TABLE "platform"."graph_sync_cursors" (
	"source_name" text PRIMARY KEY NOT NULL,
	"cursor_time" timestamp with time zone,
	"cursor_pk" text,
	"last_run_id" text,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."graph_sync_dirty_scopes" (
	"id" text PRIMARY KEY NOT NULL,
	"scope_type" text NOT NULL,
	"scope_key" text NOT NULL,
	"reason" text NOT NULL,
	"source_name" text NOT NULL,
	"source_pk" text,
	"source_progress" jsonb NOT NULL,
	"first_detected_at" timestamp with time zone NOT NULL,
	"last_detected_at" timestamp with time zone NOT NULL,
	"status" text NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"last_run_id" text,
	"error_summary" text
);
--> statement-breakpoint
CREATE TABLE "platform"."graph_sync_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"mode" text NOT NULL,
	"status" text NOT NULL,
	"scope_type" text NOT NULL,
	"scope_key" text NOT NULL,
	"trigger_type" text NOT NULL,
	"triggered_by" text NOT NULL,
	"cursor_snapshot" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"nodes_written" integer DEFAULT 0 NOT NULL,
	"edges_written" integer DEFAULT 0 NOT NULL,
	"error_summary" text,
	"error_detail" jsonb,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."job_dispatch_outbox" (
	"id" text PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"status" text NOT NULL,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"redis_stream_entry_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"published_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "platform"."job_events" (
	"id" text PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"event_type" text NOT NULL,
	"from_status" text,
	"to_status" text,
	"worker_id" text,
	"message" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"payload" jsonb NOT NULL,
	"result" jsonb,
	"error" text,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"available_at" timestamp with time zone NOT NULL,
	"locked_by" text,
	"locked_until" timestamp with time zone,
	"redis_stream_entry_id" text,
	"dispatch_status" text DEFAULT 'pending' NOT NULL,
	"owner_user_id" text,
	"organization_id" text,
	"session_id" text,
	"origin_correlation_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"failed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_approval_records" (
	"id" text PRIMARY KEY NOT NULL,
	"change_request_id" text NOT NULL,
	"decision" text NOT NULL,
	"reviewed_by" text NOT NULL,
	"comment" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_causality_edges" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"source_entity_key" text NOT NULL,
	"target_entity_key" text NOT NULL,
	"causality_type" text NOT NULL,
	"is_attribution_path_enabled" boolean DEFAULT false NOT NULL,
	"default_weight" jsonb DEFAULT '{"type":"fixed","value":1}'::jsonb NOT NULL,
	"neo4j_relationship_types" text[] DEFAULT '{}' NOT NULL,
	"temporal_constraints" jsonb,
	"filter_conditions" jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_change_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"target_object_type" text NOT NULL,
	"target_object_key" text NOT NULL,
	"change_type" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"before_summary" jsonb,
	"after_summary" jsonb,
	"impact_scope" text[] DEFAULT '{}'::text[] NOT NULL,
	"compatibility_type" text NOT NULL,
	"compatibility_note" text,
	"submitted_by" text NOT NULL,
	"submitted_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_entity_definitions" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"synonyms" text[] DEFAULT '{}' NOT NULL,
	"parent_business_key" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_evidence_type_definitions" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"evidence_category" text NOT NULL,
	"renderer_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"data_source_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"default_priority" text DEFAULT 'normal',
	"is_interactive" jsonb DEFAULT 'false'::jsonb NOT NULL,
	"template_schema" jsonb,
	"validation_rules" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_factor_definitions" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"category" text NOT NULL,
	"related_metric_keys" text[] DEFAULT '{}' NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_grounded_contexts" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"version" integer NOT NULL,
	"ontology_version_id" text NOT NULL,
	"grounding_status" text NOT NULL,
	"entities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"metrics" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"factors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"time_semantics" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"original_merged_context" text NOT NULL,
	"grounded_at" text NOT NULL,
	"grounding_strategy" text NOT NULL,
	"diagnostics" jsonb,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_metric_definitions" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"applicable_subject_keys" text[] DEFAULT '{}' NOT NULL,
	"default_aggregation" text,
	"unit" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_metric_variants" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"parent_metric_definition_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"semantic_discriminator" text NOT NULL,
	"cube_view_mapping" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"filter_template" jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_plan_step_templates" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"intent_types" text[] DEFAULT '{}' NOT NULL,
	"required_capabilities" text[] DEFAULT '{}' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_publish_records" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"published_by" text NOT NULL,
	"previous_version_id" text,
	"change_request_ids" text[] DEFAULT '{}'::text[] NOT NULL,
	"publish_note" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_time_semantics" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"business_key" text NOT NULL,
	"display_name" text NOT NULL,
	"description" text,
	"status" text NOT NULL,
	"semantic_type" text NOT NULL,
	"entity_date_field_mapping" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"cube_time_dimension_mapping" jsonb,
	"calculation_rule" jsonb,
	"default_granularity" text DEFAULT 'month',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_tool_capability_bindings" (
	"id" text PRIMARY KEY NOT NULL,
	"ontology_version_id" text NOT NULL,
	"bound_step_template_key" text,
	"bound_capability_tag" text,
	"tool_name" text NOT NULL,
	"activation_conditions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"description" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"priority" integer DEFAULT 50 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	"created_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."ontology_versions" (
	"id" text PRIMARY KEY NOT NULL,
	"semver" text NOT NULL,
	"display_name" text NOT NULL,
	"status" text NOT NULL,
	"description" text,
	"published_at" timestamp with time zone,
	"deprecated_at" timestamp with time zone,
	"retired_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "platform"."job_dispatch_outbox" ADD CONSTRAINT "job_dispatch_outbox_job_id_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "platform"."jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform"."job_events" ADD CONSTRAINT "job_events_job_id_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "platform"."jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform"."ontology_approval_records" ADD CONSTRAINT "ontology_approval_records_change_request_id_ontology_change_requests_id_fk" FOREIGN KEY ("change_request_id") REFERENCES "platform"."ontology_change_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform"."ontology_change_requests" ADD CONSTRAINT "ontology_change_requests_ontology_version_id_ontology_versions_id_fk" FOREIGN KEY ("ontology_version_id") REFERENCES "platform"."ontology_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform"."ontology_publish_records" ADD CONSTRAINT "ontology_publish_records_ontology_version_id_ontology_versions_id_fk" FOREIGN KEY ("ontology_version_id") REFERENCES "platform"."ontology_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "analysis_execution_snapshots_session_id_idx" ON "platform"."analysis_execution_snapshots" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "analysis_execution_snapshots_owner_updated_idx" ON "platform"."analysis_execution_snapshots" USING btree ("owner_user_id","updated_at");--> statement-breakpoint
CREATE INDEX "analysis_execution_snapshots_follow_up_id_idx" ON "platform"."analysis_execution_snapshots" USING btree ("follow_up_id");--> statement-breakpoint
CREATE INDEX "analysis_execution_snapshots_ontology_version_idx" ON "platform"."analysis_execution_snapshots" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_session_idx" ON "platform"."analysis_session_follow_ups" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_owner_session_idx" ON "platform"."analysis_session_follow_ups" USING btree ("owner_user_id","session_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_session_created_order_idx" ON "platform"."analysis_session_follow_ups" USING btree ("session_id","created_order");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_execution_idx" ON "platform"."analysis_session_follow_ups" USING btree ("referenced_execution_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_result_execution_idx" ON "platform"."analysis_session_follow_ups" USING btree ("result_execution_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_ontology_version_idx" ON "platform"."analysis_session_follow_ups" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "analysis_session_follow_ups_created_at_idx" ON "platform"."analysis_session_follow_ups" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "analysis_sessions_owner_user_id_idx" ON "platform"."analysis_sessions" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "analysis_sessions_org_owner_idx" ON "platform"."analysis_sessions" USING btree ("organization_id","owner_user_id");--> statement-breakpoint
CREATE INDEX "analysis_sessions_updated_at_idx" ON "platform"."analysis_sessions" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "analysis_ui_message_projection_owner_session_idx" ON "platform"."analysis_ui_message_projections" USING btree ("owner_user_id","session_id");--> statement-breakpoint
CREATE INDEX "analysis_ui_message_projection_owner_execution_idx" ON "platform"."analysis_ui_message_projections" USING btree ("owner_user_id","execution_id");--> statement-breakpoint
CREATE INDEX "analysis_ui_message_projection_session_round_idx" ON "platform"."analysis_ui_message_projections" USING btree ("session_id","history_round_id");--> statement-breakpoint
CREATE INDEX "analysis_ui_message_projection_follow_up_idx" ON "platform"."analysis_ui_message_projections" USING btree ("follow_up_id");--> statement-breakpoint
CREATE INDEX "analysis_ui_message_projection_updated_idx" ON "platform"."analysis_ui_message_projections" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "audit_events_user_id_idx" ON "platform"."audit_events" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_events_session_id_idx" ON "platform"."audit_events" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "audit_events_event_type_idx" ON "platform"."audit_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "audit_events_created_at_idx" ON "platform"."audit_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "audit_events_retention_until_idx" ON "platform"."audit_events" USING btree ("retention_until");--> statement-breakpoint
CREATE INDEX "audit_events_correlation_id_idx" ON "platform"."audit_events" USING btree ("correlation_id");--> statement-breakpoint
CREATE INDEX "auth_sessions_user_id_idx" ON "platform"."auth_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "auth_sessions_expires_at_idx" ON "platform"."auth_sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "erp_charge_items_org_idx" ON "erp_staging"."dw_datacenter_chargeitem" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "erp_houses_org_idx" ON "erp_staging"."dw_datacenter_house" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "erp_houses_precinct_idx" ON "erp_staging"."dw_datacenter_house" USING btree ("precinct_id");--> statement-breakpoint
CREATE INDEX "erp_organizations_parent_idx" ON "erp_staging"."dw_datacenter_system_organization" USING btree ("organization_parent_id");--> statement-breakpoint
CREATE INDEX "erp_organizations_path_idx" ON "erp_staging"."dw_datacenter_system_organization" USING btree ("organization_path");--> statement-breakpoint
CREATE INDEX "erp_organizations_nature_idx" ON "erp_staging"."dw_datacenter_system_organization" USING btree ("organization_nature");--> statement-breakpoint
CREATE INDEX "erp_owners_owner_idx" ON "erp_staging"."dw_datacenter_owner" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "erp_owners_project_idx" ON "erp_staging"."dw_datacenter_owner" USING btree ("precinct_id");--> statement-breakpoint
CREATE INDEX "erp_payments_project_idx" ON "erp_staging"."dw_datacenter_bill" USING btree ("precinct_id");--> statement-breakpoint
CREATE INDEX "erp_payments_owner_idx" ON "erp_staging"."dw_datacenter_bill" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "erp_precincts_org_idx" ON "erp_staging"."dw_datacenter_precinct" USING btree ("org_id");--> statement-breakpoint
CREATE INDEX "erp_precincts_area_idx" ON "erp_staging"."dw_datacenter_precinct" USING btree ("area_id");--> statement-breakpoint
CREATE INDEX "erp_precincts_org_fk_idx" ON "erp_staging"."dw_datacenter_precinct" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "erp_receivables_project_idx" ON "erp_staging"."dw_datacenter_charge" USING btree ("precinct_id");--> statement-breakpoint
CREATE INDEX "erp_receivables_owner_idx" ON "erp_staging"."dw_datacenter_charge" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "erp_service_orders_project_idx" ON "erp_staging"."dw_datacenter_services" USING btree ("precinct_id");--> statement-breakpoint
CREATE INDEX "erp_service_orders_style_idx" ON "erp_staging"."dw_datacenter_services" USING btree ("service_style_name");--> statement-breakpoint
CREATE INDEX "erp_system_users_org_idx" ON "erp_staging"."dw_datacenter_system_user" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "erp_system_users_account_idx" ON "erp_staging"."dw_datacenter_system_user" USING btree ("user_account");--> statement-breakpoint
CREATE INDEX "erp_system_users_phone_idx" ON "erp_staging"."dw_datacenter_system_user" USING btree ("user_telephone");--> statement-breakpoint
CREATE INDEX "job_dispatch_outbox_status_updated_at_idx" ON "platform"."job_dispatch_outbox" USING btree ("status","updated_at");--> statement-breakpoint
CREATE INDEX "job_dispatch_outbox_job_id_idx" ON "platform"."job_dispatch_outbox" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "job_events_job_id_created_at_idx" ON "platform"."job_events" USING btree ("job_id","created_at");--> statement-breakpoint
CREATE INDEX "job_events_event_type_created_at_idx" ON "platform"."job_events" USING btree ("event_type","created_at");--> statement-breakpoint
CREATE INDEX "jobs_status_available_at_idx" ON "platform"."jobs" USING btree ("status","available_at");--> statement-breakpoint
CREATE INDEX "jobs_locked_until_idx" ON "platform"."jobs" USING btree ("locked_until");--> statement-breakpoint
CREATE INDEX "jobs_owner_user_id_idx" ON "platform"."jobs" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "jobs_session_id_idx" ON "platform"."jobs" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "jobs_dispatch_status_idx" ON "platform"."jobs" USING btree ("dispatch_status","updated_at");--> statement-breakpoint
CREATE INDEX "jobs_created_at_idx" ON "platform"."jobs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "ontology_approval_records_change_request_id_idx" ON "platform"."ontology_approval_records" USING btree ("change_request_id");--> statement-breakpoint
CREATE INDEX "ontology_approval_records_reviewed_by_idx" ON "platform"."ontology_approval_records" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "ontology_approval_records_decision_idx" ON "platform"."ontology_approval_records" USING btree ("decision");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_version_idx" ON "platform"."ontology_causality_edges" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_business_key_idx" ON "platform"."ontology_causality_edges" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_version_key_idx" ON "platform"."ontology_causality_edges" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_status_idx" ON "platform"."ontology_causality_edges" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_source_idx" ON "platform"."ontology_causality_edges" USING btree ("source_entity_key");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_target_idx" ON "platform"."ontology_causality_edges" USING btree ("target_entity_key");--> statement-breakpoint
CREATE INDEX "ontology_causality_edges_attribution_idx" ON "platform"."ontology_causality_edges" USING btree ("is_attribution_path_enabled");--> statement-breakpoint
CREATE INDEX "ontology_change_requests_version_id_idx" ON "platform"."ontology_change_requests" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_change_requests_status_idx" ON "platform"."ontology_change_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_change_requests_submitted_by_idx" ON "platform"."ontology_change_requests" USING btree ("submitted_by");--> statement-breakpoint
CREATE INDEX "ontology_change_requests_target_idx" ON "platform"."ontology_change_requests" USING btree ("target_object_type","target_object_key");--> statement-breakpoint
CREATE INDEX "ontology_entity_defs_version_idx" ON "platform"."ontology_entity_definitions" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_entity_defs_business_key_idx" ON "platform"."ontology_entity_definitions" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_entity_defs_version_key_idx" ON "platform"."ontology_entity_definitions" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_entity_defs_status_idx" ON "platform"."ontology_entity_definitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_evidence_type_defs_version_idx" ON "platform"."ontology_evidence_type_definitions" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_evidence_type_defs_business_key_idx" ON "platform"."ontology_evidence_type_definitions" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_evidence_type_defs_version_key_idx" ON "platform"."ontology_evidence_type_definitions" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_evidence_type_defs_category_idx" ON "platform"."ontology_evidence_type_definitions" USING btree ("evidence_category");--> statement-breakpoint
CREATE INDEX "ontology_evidence_type_defs_status_idx" ON "platform"."ontology_evidence_type_definitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_factor_defs_version_idx" ON "platform"."ontology_factor_definitions" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_factor_defs_business_key_idx" ON "platform"."ontology_factor_definitions" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_factor_defs_version_key_idx" ON "platform"."ontology_factor_definitions" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_factor_defs_category_idx" ON "platform"."ontology_factor_definitions" USING btree ("category");--> statement-breakpoint
CREATE INDEX "ontology_factor_defs_status_idx" ON "platform"."ontology_factor_definitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_metric_defs_version_idx" ON "platform"."ontology_metric_definitions" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_metric_defs_business_key_idx" ON "platform"."ontology_metric_definitions" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_metric_defs_version_key_idx" ON "platform"."ontology_metric_definitions" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_metric_defs_status_idx" ON "platform"."ontology_metric_definitions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_metric_variants_version_idx" ON "platform"."ontology_metric_variants" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_metric_variants_parent_metric_idx" ON "platform"."ontology_metric_variants" USING btree ("parent_metric_definition_id");--> statement-breakpoint
CREATE INDEX "ontology_metric_variants_business_key_idx" ON "platform"."ontology_metric_variants" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_metric_variants_version_key_idx" ON "platform"."ontology_metric_variants" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_metric_variants_status_idx" ON "platform"."ontology_metric_variants" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_plan_step_tmpl_version_idx" ON "platform"."ontology_plan_step_templates" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_plan_step_tmpl_business_key_idx" ON "platform"."ontology_plan_step_templates" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_plan_step_tmpl_version_key_idx" ON "platform"."ontology_plan_step_templates" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_plan_step_tmpl_status_idx" ON "platform"."ontology_plan_step_templates" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_publish_records_version_id_idx" ON "platform"."ontology_publish_records" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_publish_records_published_by_idx" ON "platform"."ontology_publish_records" USING btree ("published_by");--> statement-breakpoint
CREATE INDEX "ontology_time_semantics_version_idx" ON "platform"."ontology_time_semantics" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE INDEX "ontology_time_semantics_business_key_idx" ON "platform"."ontology_time_semantics" USING btree ("business_key");--> statement-breakpoint
CREATE INDEX "ontology_time_semantics_version_key_idx" ON "platform"."ontology_time_semantics" USING btree ("ontology_version_id","business_key");--> statement-breakpoint
CREATE INDEX "ontology_time_semantics_type_idx" ON "platform"."ontology_time_semantics" USING btree ("semantic_type");--> statement-breakpoint
CREATE INDEX "ontology_time_semantics_status_idx" ON "platform"."ontology_time_semantics" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_versions_status_idx" ON "platform"."ontology_versions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ontology_versions_published_at_idx" ON "platform"."ontology_versions" USING btree ("published_at");

CREATE INDEX "analysis_execution_snapshots_session_updated_idx" ON "platform"."analysis_execution_snapshots" USING btree ("session_id","updated_at" DESC);

CREATE TABLE "platform"."agent_invocations" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"execution_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"agent_name" text NOT NULL,
	"tool_name" text NOT NULL,
	"kind" text NOT NULL,
	"parent_invocation_id" text,
	"input" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"output" jsonb,
	"status" text NOT NULL,
	"error_code" text,
	"error_message" text,
	"trace_id" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform"."analysis_execution_events" (
	"id" text PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"execution_id" text NOT NULL,
	"owner_user_id" text NOT NULL,
	"sequence" bigint NOT NULL,
	"kind" text NOT NULL,
	"event_timestamp" timestamp with time zone NOT NULL,
	"status" text,
	"message" text,
	"render_blocks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"error_code" text,
	"trace_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "platform"."analysis_execution_snapshots" ADD COLUMN "error_code" text;--> statement-breakpoint
ALTER TABLE "platform"."analysis_execution_snapshots" ADD COLUMN "trace_id" text;--> statement-breakpoint
CREATE INDEX "agent_invocations_execution_kind_tool_idx" ON "platform"."agent_invocations" USING btree ("execution_id","kind","tool_name");--> statement-breakpoint
CREATE INDEX "agent_invocations_trace_idx" ON "platform"."agent_invocations" USING btree ("trace_id");--> statement-breakpoint
CREATE INDEX "agent_invocations_parent_idx" ON "platform"."agent_invocations" USING btree ("parent_invocation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "analysis_execution_events_execution_sequence_uidx" ON "platform"."analysis_execution_events" USING btree ("execution_id","sequence");--> statement-breakpoint
CREATE INDEX "analysis_execution_events_access_idx" ON "platform"."analysis_execution_events" USING btree ("session_id","execution_id","owner_user_id","sequence");--> statement-breakpoint
CREATE INDEX "analysis_execution_snapshots_trace_id_idx" ON "platform"."analysis_execution_snapshots" USING btree ("trace_id");

CREATE UNIQUE INDEX "agent_invocations_agent_run_uidx" ON "platform"."agent_invocations" USING btree ("execution_id") WHERE kind = 'agent-run';

CREATE TABLE "spring_ai_chat_memory" (
	"conversation_id" varchar(36) NOT NULL,
	"content" text NOT NULL,
	"type" varchar(10) NOT NULL,
	"timestamp" timestamp NOT NULL,
	"sequence_id" bigint NOT NULL,
	CONSTRAINT "spring_ai_chat_memory_type_check" CHECK (type in ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);
--> statement-breakpoint
CREATE INDEX "spring_ai_chat_memory_conversation_id_timestamp_idx" ON "spring_ai_chat_memory" USING btree ("conversation_id","timestamp");--> statement-breakpoint
CREATE INDEX "spring_ai_chat_memory_conversation_id_sequence_id_idx" ON "spring_ai_chat_memory" USING btree ("conversation_id","sequence_id");--> statement-breakpoint
CREATE UNIQUE INDEX "analysis_execution_snapshots_follow_up_id_uidx" ON "platform"."analysis_execution_snapshots" USING btree ("follow_up_id") WHERE follow_up_id is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "analysis_session_follow_ups_result_execution_uidx" ON "platform"."analysis_session_follow_ups" USING btree ("result_execution_id") WHERE result_execution_id is not null;

CREATE UNIQUE INDEX "ontology_publish_records_version_uidx" ON "platform"."ontology_publish_records" USING btree ("ontology_version_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ontology_versions_single_current_uidx" ON "platform"."ontology_versions" USING btree ("status") WHERE status = 'approved' and published_at is not null;
