import {
  bigint,
  date,
  index,
  integer,
  numeric,
  pgSchema,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

export const erpStagingSchema = pgSchema('erp_staging');

export const erpOrganizations = erpStagingSchema.table(
  'dw_datacenter_system_organization',
  {
    sourceId: bigint('source_id', { mode: 'bigint' }).primaryKey(),
    enterpriseId: bigint('enterprise_id', { mode: 'bigint' }),
    groupId: bigint('group_id', { mode: 'bigint' }),
    companyId: bigint('company_id', { mode: 'bigint' }),
    departmentId: bigint('department_id', { mode: 'bigint' }),
    organizationParentId: bigint('organization_parent_id', { mode: 'bigint' }),
    organizationName: text('organization_name').notNull(),
    organizationShortName: text('organization_short_name'),
    organizationCode: text('organization_code'),
    organizationType: integer('organization_type'),
    organizationEnableState: integer('organization_enable_state'),
    organizationPath: text('organization_path'),
    organizationLevel: integer('organization_level'),
    organizationOrderColumn: integer('organization_order_column'),
    isDeleted: integer('is_deleted'),
    remark: text('remark'),
    versionId: bigint('version_id', { mode: 'bigint' }),
    createUserId: bigint('create_user_id', { mode: 'bigint' }),
    createUserName: text('create_user_name'),
    createTime: timestamp('create_time', { withTimezone: true }),
    updateUserId: bigint('update_user_id', { mode: 'bigint' }),
    updateUserName: text('update_user_name'),
    updateTime: timestamp('update_time', { withTimezone: true }),
    syncDepartmentId: text('sync_department_id'),
    syncOrganizationId: text('sync_organization_id'),
    syncOrganizationParentId: text('sync_organization_parent_id'),
    syncStatus: integer('sync_status'),
    organizationDimension: text('organization_dimension'),
    organizationDimensionAliasName: text('organization_dimension_alias_name'),
    organizationScope: text('organization_scope'),
    organizationManagerId: text('organization_manager_id'),
    organizationPartManagerId: text('organization_part_manager_id'),
    organizationHrTypeCode: text('organization_hr_type_code'),
    organizationHierarchicalClassCode: text(
      'organization_hierarchical_class_code',
    ),
    organizationStageCode: text('organization_stage_code'),
    organizationStageLevelCode: text('organization_stage_level_code'),
    organizationSource: text('organization_source'),
    organizationNature: text('organization_nature'),
    dataAnalysisType: text('data_analysis_type'),
    sysDate: date('sys_date'),
  },
  (table) => [
    index('erp_organizations_parent_idx').on(table.organizationParentId),
    index('erp_organizations_path_idx').on(table.organizationPath),
    index('erp_organizations_nature_idx').on(table.organizationNature),
  ],
);

export const erpPrecincts = erpStagingSchema.table(
  'dw_datacenter_precinct',
  {
    recordId: bigint('record_id', { mode: 'bigint' }),
    enterpriseId: text('enterprise_id'),
    dataSource: text('data_source'),
    orgId: text('org_id'),
    areaId: text('area_id'),
    areaName: text('area_name'),
    precinctId: text('precinct_id').primaryKey(),
    precinctNo: text('precinct_no'),
    precinctName: text('precinct_name').notNull(),
    deliveryTime: timestamp('delivery_time', { withTimezone: true }),
    provinceId: text('province_id'),
    cityId: text('city_id'),
    areaCityId: text('area_city_id'),
    streetId: text('street_id'),
    proNature: text('pro_nature'),
    checkMerger: text('check_merger'),
    checkOldPrecinct: text('check_old_precinct'),
    oldTaxRate: numeric('old_tax_rate', { precision: 3, scale: 2 }),
    precinctType: text('precinct_type'),
    precinctTypeName: text('precinct_type_name'),
    isDelete: integer('is_delete'),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    contractArea: numeric('contract_area'),
    greenArea: numeric('green_area'),
    nozzleArea: numeric('nozzle_area'),
    payChargeArea: numeric('pay_charge_area'),
    precinctArea: text('precinct_area'),
    totalHouseHolder: integer('total_house_holder'),
    parkingAmount: integer('parking_amount'),
    organizationId: bigint('organization_id', { mode: 'bigint' }),
    deleteFlag: integer('delete_flag'),
    createUserId: bigint('create_user_id', { mode: 'bigint' }),
    createUserName: text('create_user_name'),
    createDateTime: date('create_date_time'),
    updateUserId: bigint('update_user_id', { mode: 'bigint' }),
    updateUserName: text('update_user_name'),
    updateDateTime: date('update_date_time'),
  },
  (table) => [
    index('erp_precincts_org_idx').on(table.orgId),
    index('erp_precincts_area_idx').on(table.areaId),
    index('erp_precincts_org_fk_idx').on(table.organizationId),
  ],
);

export const erpOwners = erpStagingSchema.table(
  'dw_datacenter_owner',
  {
    recordId: bigint('record_id', { mode: 'bigint' }).primaryKey(),
    enterpriseId: text('enterprise_id'),
    dataSource: text('data_source'),
    orgId: text('org_id'),
    precinctId: text('precinct_id').notNull(),
    precinctName: text('precinct_name'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    ownerId: text('owner_id').notNull(),
    ownerName: text('owner_name').notNull(),
    ownerType: text('owner_type'),
    isCurrent: text('is_current'),
    isDelete: integer('is_delete'),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
  },
  (table) => [
    index('erp_owners_owner_idx').on(table.ownerId),
    index('erp_owners_project_idx').on(table.precinctId),
  ],
);

export const erpChargeItems = erpStagingSchema.table(
  'dw_datacenter_chargeitem',
  {
    recordId: bigint('record_id', { mode: 'bigint' }),
    enterpriseId: text('enterprise_id'),
    organizationId: text('organization_id'),
    dataSource: text('data_source'),
    chargeItemId: text('charge_item_id').primaryKey(),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name').notNull(),
    chargeItemType: text('charge_item_type'),
    chargeItemTypeName: text('charge_item_type_name'),
    taxRate: numeric('tax_rate', { precision: 3, scale: 2 }),
    itemGroupId: bigint('item_group_id', { mode: 'bigint' }),
    itemDetailGroupId: bigint('item_detail_group_id', { mode: 'bigint' }),
    cashFlowGroupId: bigint('cash_flow_group_id', { mode: 'bigint' }),
    chargeItemClass: integer('charge_item_class'),
    chargeItemClassName: text('charge_item_class_name'),
    path: text('path'),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    deleteFlag: integer('delete_flag'),
    createUserId: bigint('create_user_id', { mode: 'bigint' }),
    createUserName: text('create_user_name'),
    createDateTime: date('create_date_time'),
    updateUserId: bigint('update_user_id', { mode: 'bigint' }),
    updateUserName: text('update_user_name'),
    updateDateTime: date('update_date_time'),
    chargeItemOutType: text('charge_item_out_type'),
    oneLevelChargeItemName: text('one_level_charge_item_name'),
  },
  (table) => [index('erp_charge_items_org_idx').on(table.organizationId)],
);

export const erpReceivables = erpStagingSchema.table(
  'dw_datacenter_charge',
  {
    recordId: bigint('record_id', { mode: 'bigint' }).primaryKey(),
    dbId: integer('db_id'),
    enterpriseId: text('enterprise_id'),
    organizationId: text('organization_id').notNull(),
    dataSource: text('data_source'),
    chargeDetailId: text('charge_detail_id'),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    roomType: text('room_type'),
    chargeArea: numeric('charge_area'),
    ownerId: text('owner_id'),
    ownerName: text('owner_name'),
    chargeItemId: text('charge_item_id'),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name'),
    shouldAccountBook: integer('should_account_book'),
    shouldChargeDate: timestamp('should_charge_date', { withTimezone: true }),
    calcStartDate: timestamp('calc_start_date', { withTimezone: true }),
    calcEndDate: timestamp('calc_end_date', { withTimezone: true }),
    calcEndYear: integer('calc_end_year'),
    amount: numeric('amount'),
    actualChargeSum: numeric('actual_charge_sum'),
    chargeSum: numeric('charge_sum'),
    discount: numeric('discount'),
    delaySum: numeric('delay_sum'),
    delayDiscount: numeric('delay_discount'),
    paidChargeSum: numeric('paid_charge_sum'),
    arrears: numeric('arrears'),
    isCheck: text('is_check'),
    isEstate: integer('is_estate'),
    isDelete: integer('is_delete'),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    isFreezed: integer('is_freezed'),
    discountDate: timestamp('discount_date', { withTimezone: true }),
  },
  (table) => [
    index('erp_receivables_project_idx').on(table.precinctId),
    index('erp_receivables_owner_idx').on(table.ownerId),
  ],
);

export const erpPayments = erpStagingSchema.table(
  'dw_datacenter_bill',
  {
    recordId: bigint('record_id', { mode: 'bigint' }).primaryKey(),
    dbId: integer('db_id'),
    enterpriseId: text('enterprise_id'),
    organizationId: text('organization_id').notNull(),
    dataSource: text('data_source'),
    chargePaymentId: text('charge_payment_id'),
    chargeDetailId: text('charge_detail_id'),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    roomType: text('room_type'),
    ownerId: text('owner_id'),
    ownerName: text('owner_name'),
    chargeItemId: text('charge_item_id'),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name'),
    calcStartDate: timestamp('calc_start_date', { withTimezone: true }),
    calcEndDate: timestamp('calc_end_date', { withTimezone: true }),
    calcEndYear: integer('calc_end_year'),
    shouldAccountBook: integer('should_account_book'),
    accountBook: integer('account_book'),
    actualAccountBook: integer('actual_account_book'),
    chargePaid: numeric('charge_paid'),
    discount: numeric('discount'),
    delaySum: numeric('delay_sum'),
    operatorDate: timestamp('operator_date', { withTimezone: true }),
    paidYear: integer('paid_year'),
    paidMonth: integer('paid_month'),
    paidDay: integer('paid_day'),
    isEnterAccount: text('is_enter_account'),
    chargeArea: numeric('charge_area'),
    subjectCode: text('subject_code'),
    sourceIncome: text('source_income'),
    squareTypeId: text('square_type_id'),
    squareTypeName: text('square_type_name'),
    isCanceled: text('is_canceled'),
    isDelete: integer('is_delete'),
    dataType: integer('data_type'),
    precinctCollectionType: integer('precinct_collection_type'),
    refundStatus: text('refund_status'),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    isAccount: integer('is_account'),
  },
  (table) => [
    index('erp_payments_project_idx').on(table.precinctId),
    index('erp_payments_owner_idx').on(table.ownerId),
  ],
);

export const erpServiceOrders = erpStagingSchema.table(
  'dw_datacenter_services',
  {
    recordId: bigint('record_id', { mode: 'bigint' }),
    enterpriseId: text('enterprise_id'),
    organizationId: text('organization_id').notNull(),
    dataSource: text('data_source'),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    houseId: text('house_id'),
    customerId: integer('customer_id'),
    customerHouseId: integer('customer_house_id'),
    customerHouseName: text('customer_house_name'),
    customerName: text('customer_name'),
    houseName: text('house_name'),
    servicesNo: text('services_no').primaryKey(),
    content: text('content'),
    createUserName: text('create_user_name'),
    createDateTime: timestamp('create_date_time', { withTimezone: true }),
    updateDateTime: timestamp('update_date_time', { withTimezone: true }),
    isDelete: integer('is_delete'),
    createYear: integer('create_year'),
    createMonth: integer('create_month'),
    dispatchingUserName: text('dispatching_user_name'),
    dispatchingDate: timestamp('dispatching_date', { withTimezone: true }),
    acceptUserName: text('accept_user_name'),
    acceptDate: timestamp('accept_date', { withTimezone: true }),
    arriveDate: timestamp('arrive_date', { withTimezone: true }),
    receptionDate: timestamp('reception_date', { withTimezone: true }),
    accomplishUserName: text('accomplish_user_name'),
    accomplishDate: timestamp('accomplish_date', { withTimezone: true }),
    serviceStatus: text('service_status'),
    serviceStatusName: text('service_status_name'),
    serviceTypeId: text('service_type_id'),
    serviceTypeName: text('service_type_name'),
    serviceSourceId: text('service_source_id'),
    serviceSourceName: text('service_source_name'),
    serviceStyleId: text('service_style_id'),
    serviceStyleName: text('service_style_name'),
    isCompleted: text('is_completed'),
    isOverTime: text('is_over_time'),
    isReprocess: text('is_reprocess'),
    isReturnVisit: text('is_return_visit'),
    satisfaction: integer('satisfaction'),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    acceptOverTime: integer('accept_over_time'),
    satisfactionEval: integer('satisfaction_eval'),
    servicePayTypeId: integer('service_pay_type_id'),
    oneTypeName: text('one_type_name'),
    secondTypeName: text('second_type_name'),
    threeTypeName: text('three_type_name'),
    serviceKindId: text('service_kind_id'),
    serviceKindIdName: text('service_kind_id_name'),
  },
  (table) => [
    index('erp_service_orders_project_idx').on(table.precinctId),
    index('erp_service_orders_style_idx').on(table.serviceStyleName),
  ],
);

export const erpHouses = erpStagingSchema.table(
  'dw_datacenter_house',
  {
    recordId: bigint('record_id', { mode: 'bigint' }),
    enterpriseId: text('enterprise_id'),
    dataSource: text('data_source'),
    orgId: text('org_id'),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    houseId: text('house_id').primaryKey(),
    houseName: text('house_name'),
    roomType: text('room_type'),
    roomTypeName: text('room_type_name'),
    houseType: text('house_type'),
    chargeArea: numeric('charge_area'),
    buildArea: numeric('build_area'),
    isShow: integer('is_show'),
    isSpilt: integer('is_spilt'),
    isVirtual: integer('is_virtual'),
    stage: text('stage'),
    rentStage: text('rent_stage'),
    decorateStage: text('decorate_stage'),
    buildingId: text('building_id'),
    regionalCompanyId: text('regional_company_id'),
    areaId: text('area_id'),
    clusterId: text('cluster_id'),
    businessClusterId: text('business_cluster_id'),
    unitId: text('unit_id'),
    isDelete: integer('is_delete'),
    isBlockUp: integer('is_block_up'),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    syncDate: timestamp('sync_date', { withTimezone: true }),
  },
  (table) => [
    index('erp_houses_org_idx').on(table.orgId),
    index('erp_houses_precinct_idx').on(table.precinctId),
  ],
);

export const erpSystemUsers = erpStagingSchema.table(
  'dw_datacenter_system_user',
  {
    sourceId: bigint('source_id', { mode: 'bigint' }).primaryKey(),
    enterpriseId: bigint('enterprise_id', { mode: 'bigint' }),
    organizationId: bigint('organization_id', { mode: 'bigint' }),
    groupId: bigint('group_id', { mode: 'bigint' }),
    companyId: bigint('company_id', { mode: 'bigint' }),
    departmentId: bigint('department_id', { mode: 'bigint' }),
    sentryId: text('sentry_id'),
    sentryName: text('sentry_name'),
    userAccount: text('user_account'),
    password: text('password'),
    userTelephone: text('user_telephone'),
    userPassword: text('user_password'),
    userBirthday: timestamp('user_birthday', { withTimezone: true }),
    userHiredate: timestamp('user_hiredate', { withTimezone: true }),
    userState: text('user_state'),
    userType: integer('user_type'),
    userCertificateType: text('user_certificate_type'),
    userCertificateNumber: text('user_certificate_number'),
    userPicurl: text('user_picurl'),
    isDeleted: integer('is_deleted'),
    isActived: text('is_actived'),
    remark: text('remark'),
    enable2FA: integer('enable2_fa'),
    qwUserId: text('qw_user_id'),
    qwOpenId: text('qw_open_id'),
    syncDate: timestamp('sync_date', { withTimezone: true }),
    sysDate: date('sys_date'),
  },
  (table) => [
    index('erp_system_users_org_idx').on(table.organizationId),
    index('erp_system_users_account_idx').on(table.userAccount),
    index('erp_system_users_phone_idx').on(table.userTelephone),
  ],
);
