import {
  index,
  integer,
  numeric,
  pgSchema,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

export const erpStagingSchema = pgSchema('erp_staging');

export const erpOrganizations = erpStagingSchema.table(
  'dw_datacenter_system_organization',
  {
    sourceId: text('source_id').primaryKey(),
    organizationParentId: text('organization_parent_id'),
    organizationPath: text('organization_path'),
    organizationLevel: integer('organization_level'),
    organizationName: text('organization_name').notNull(),
    organizationShortName: text('organization_short_name'),
    organizationNature: text('organization_nature'),
    enterpriseId: text('enterprise_id'),
    groupId: text('group_id'),
    companyId: text('company_id'),
    departmentId: text('department_id'),
    organizationEnableState: text('organization_enable_state'),
    isDeleted: text('is_deleted'),
  },
  (table) => [
    index('erp_organizations_parent_idx').on(table.organizationParentId),
    index('erp_organizations_path_idx').on(table.organizationPath),
  ],
);

export const erpPrecincts = erpStagingSchema.table(
  'dw_datacenter_precinct',
  {
    precinctId: text('precinct_id').primaryKey(),
    precinctNo: text('precinct_no'),
    precinctName: text('precinct_name').notNull(),
    orgId: text('org_id').notNull(),
    organizationId: text('organization_id'),
    enterpriseId: text('enterprise_id'),
    areaId: text('area_id'),
    areaName: text('area_name'),
    precinctType: text('precinct_type'),
    precinctTypeName: text('precinct_type_name'),
    deliveryTime: timestamp('delivery_time', { withTimezone: true }),
    contractArea: numeric('contract_area'),
    nozzleArea: numeric('nozzle_area'),
    payChargeArea: numeric('pay_charge_area'),
    totalHouseHolder: integer('total_house_holder'),
    isDelete: text('is_delete'),
    deleteFlag: text('delete_flag'),
  },
  (table) => [
    index('erp_precincts_org_idx').on(table.orgId),
    index('erp_precincts_area_idx').on(table.areaId),
  ],
);

export const erpOwners = erpStagingSchema.table(
  'dw_datacenter_owner',
  {
    recordId: text('record_id').primaryKey(),
    ownerId: text('owner_id').notNull(),
    ownerName: text('owner_name').notNull(),
    ownerType: text('owner_type'),
    isCurrent: text('is_current'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    precinctId: text('precinct_id').notNull(),
    precinctName: text('precinct_name'),
    orgId: text('org_id').notNull(),
    areaId: text('area_id'),
  },
  (table) => [
    index('erp_owners_owner_idx').on(table.ownerId),
    index('erp_owners_project_idx').on(table.precinctId),
  ],
);

export const erpChargeItems = erpStagingSchema.table(
  'dw_datacenter_chargeitem',
  {
    chargeItemId: text('charge_item_id').primaryKey(),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name').notNull(),
    chargeItemType: text('charge_item_type'),
    chargeItemTypeName: text('charge_item_type_name'),
    chargeItemClass: text('charge_item_class'),
    chargeItemClassName: text('charge_item_class_name'),
    oneLevelChargeItemName: text('one_level_charge_item_name'),
    organizationId: text('organization_id').notNull(),
  },
  (table) => [index('erp_charge_items_org_idx').on(table.organizationId)],
);

export const erpReceivables = erpStagingSchema.table(
  'dw_datacenter_charge',
  {
    recordId: text('record_id').primaryKey(),
    organizationId: text('organization_id').notNull(),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    areaId: text('area_id'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    ownerId: text('owner_id'),
    ownerName: text('owner_name'),
    chargeItemId: text('charge_item_id'),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name'),
    chargeSum: numeric('charge_sum'),
    actualChargeSum: numeric('actual_charge_sum'),
    paidChargeSum: numeric('paid_charge_sum'),
    arrears: numeric('arrears'),
    discount: numeric('discount'),
    delaySum: numeric('delay_sum'),
    delayDiscount: numeric('delay_discount'),
    shouldChargeDate: timestamp('should_charge_date', { withTimezone: true }),
    calcStartDate: timestamp('calc_start_date', { withTimezone: true }),
    calcEndDate: timestamp('calc_end_date', { withTimezone: true }),
    createDate: timestamp('create_date', { withTimezone: true }),
    updateDate: timestamp('update_date', { withTimezone: true }),
    isCheck: text('is_check'),
    isDelete: text('is_delete'),
    isFreezed: text('is_freezed'),
  },
  (table) => [
    index('erp_receivables_project_idx').on(table.precinctId),
    index('erp_receivables_owner_idx').on(table.ownerId),
  ],
);

export const erpPayments = erpStagingSchema.table(
  'dw_datacenter_bill',
  {
    recordId: text('record_id').primaryKey(),
    organizationId: text('organization_id').notNull(),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    areaId: text('area_id'),
    houseId: text('house_id'),
    houseName: text('house_name'),
    ownerId: text('owner_id'),
    ownerName: text('owner_name'),
    chargeItemId: text('charge_item_id'),
    chargeItemCode: text('charge_item_code'),
    chargeItemName: text('charge_item_name'),
    chargeDetailId: text('charge_detail_id'),
    chargePaid: numeric('charge_paid'),
    discount: numeric('discount'),
    delaySum: numeric('delay_sum'),
    operatorDate: timestamp('operator_date', { withTimezone: true }),
    calcStartDate: timestamp('calc_start_date', { withTimezone: true }),
    calcEndDate: timestamp('calc_end_date', { withTimezone: true }),
    isEnterAccount: text('is_enter_account'),
    isCanceled: text('is_canceled'),
    dataType: text('data_type'),
    refundStatus: text('refund_status'),
    isAccount: text('is_account'),
    isDelete: text('is_delete'),
  },
  (table) => [
    index('erp_payments_project_idx').on(table.precinctId),
    index('erp_payments_owner_idx').on(table.ownerId),
  ],
);

export const erpServiceOrders = erpStagingSchema.table(
  'dw_datacenter_services',
  {
    servicesNo: text('services_no').primaryKey(),
    organizationId: text('organization_id').notNull(),
    organizationPath: text('organization_path'),
    precinctId: text('precinct_id'),
    precinctName: text('precinct_name'),
    areaId: text('area_id'),
    houseId: text('house_id'),
    customerId: text('customer_id'),
    customerName: text('customer_name'),
    serviceTypeId: text('service_type_id'),
    serviceTypeName: text('service_type_name'),
    serviceStyleId: text('service_style_id'),
    serviceStyleName: text('service_style_name'),
    serviceKindId: text('service_kind_id'),
    serviceKindIdName: text('service_kind_id_name'),
    serviceSourceId: text('service_source_id'),
    serviceSourceName: text('service_source_name'),
    serviceStatus: text('service_status'),
    serviceStatusName: text('service_status_name'),
    content: text('content'),
    createDateTime: timestamp('create_date_time', { withTimezone: true }),
    accomplishDate: timestamp('accomplish_date', { withTimezone: true }),
    updateDateTime: timestamp('update_date_time', { withTimezone: true }),
    satisfaction: numeric('satisfaction'),
    satisfactionEval: integer('satisfaction_eval'),
    isCompleted: text('is_completed'),
    isDelete: text('is_delete'),
  },
  (table) => [
    index('erp_service_orders_project_idx').on(table.precinctId),
    index('erp_service_orders_style_idx').on(table.serviceStyleName),
  ],
);
